[package]
name = "fel4-config"
version = "0.1.0"
authors = ["Zachary Pierce <zpierce@polysync.io>"]

[dependencies]
cmake = "0.1"
failure = "0.1"
multimap = "0.4"
toml = "0.4"

[dev-dependencies]
proptest = "0.7"
